# Generated by Django 3.1.4 on 2021-06-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('department', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='department',
            field=models.CharField(max_length=20),
        ),
    ]
