# Generated by Django 3.1.4 on 2021-06-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210611_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='department',
            field=models.CharField(max_length=30),
        ),
    ]
